language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - 0.5
  - nightly
git:
    depth: 99999
env:
    global:
    - PYTHON=conda
    matrix:
    - MPMATH=true
    - MPMATH=false
notifications:
  email: false
before_install:
  - if [ $MPMATH = "true" ]; then julia -e 'Pkg.add("Conda"); using Conda; Conda.add("mpmath")';fi
  # - sudo apt-get -qq update
  # - sudo apt-get install -y python-mpmath
  # - sudo apt-get install -y python-sympy
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("SymPy"); Pkg.test("SymPy"; coverage=true)'
